version: '3'

services:
  parser:
    container_name: scqm-parser
    build: parser
    command: ./gradlew build; java -jar build/libs/gs-spring-boot-0.1.0.jar
    volumes:
    - ../java-parser:/usr/src/java-parser:z

  model:
    container_name: scqm-model
    build: model
    command: tail -f /dev/null
    volumes:
    - ../trained:/usr/src/trained:z
    - ../scqm-model:/usr/src/scqm-model:z
    - ../scqm-input:/usr/src/scqm-input:z
    ports:
    - "7276:5000"
